#!/bin/bash
# =============================================================================
# sweep_local_pct.sh — Local memory percentage sweep: PCIe vs CXL
#
# Varies --local-pct from 0% to 100% in 10% steps.
# N=1, slots=32768, ops=100000, local memory=HBM2, host memory=DDR5-6400.
#
# Output:
#   m5out/local_pct_sweep/results.csv              — all metrics per run
#   m5out/local_pct_sweep/{fabric}_pct{P}.log      — full gem5 log per run
#   m5out/local_pct_sweep/{fabric}_pct{P}/         — gem5 stats/config per run
#   m5out/local_pct_sweep/local_pct_plot.png/pdf   — generated by plot_local_pct.py
#
# Usage:
#   cd /mnt/f/gem5
#   bash configs/sweep_local_pct.sh
#   python3 configs/plot_local_pct.py m5out/local_pct_sweep/results.csv
# =============================================================================
set -e

GEM5=build/ALL/gem5.opt
CFGDIR=configs
BIN=$CFGDIR/oram_workload
SLOTS=32768
OPS=100000            # total ops: 50k writes + 50k reads
N=1
OUTDIR=m5out/local_pct_sweep
RESULTS=$OUTDIR/results.csv

mkdir -p $OUTDIR
echo "fabric,local_pct,e2e_cyc,rtl_cyc,ddr_read_cyc,ddr_write_cyc" > $RESULTS

extract() {
    local LOG=$1
    local E2E=$(grep "cyc/op" "$LOG" | tail -1 | sed 's/.*Avg: \([0-9.]*\) cyc.*/\1/')
    local RTL=$(grep -i "RTL.*avg\|RTL.*cyc/op" "$LOG" | tail -1 | grep -oP '[0-9]+\.?[0-9]*(?=\s*cyc)' | head -1)
    local RD=$(grep "DDR_READ" "$LOG" | grep "cyc" | tail -1 | grep -oP '\d+(?=\s*cyc)')
    local WR=$(grep "DDR_WRITE" "$LOG" | grep "cyc" | tail -1 | grep -oP '\d+(?=\s*cyc)')
    echo "${E2E:-NA},${RTL:-NA},${RD:-NA},${WR:-NA}"
}

for PCT in 0 10 20 30 40 50 60 70 80 90 100; do
    echo "=== PCIe local_pct=$PCT ==="
    TAG="pcie_pct${PCT}"
    $GEM5 -d "$OUTDIR/$TAG" "$CFGDIR/oram_sim_pcie.py" \
        --binary=$BIN --num-instances=$N --num-ops=$OPS --num-slots=$SLOTS \
        --local-pct=$PCT --local-mem=hbm2 \
        2>&1 | tee "$OUTDIR/${TAG}.log" | tail -3
    VALS=$(extract "$OUTDIR/${TAG}.log")
    echo "pcie,$PCT,$VALS" >> $RESULTS
    echo "  → $VALS"

    echo "=== CXL local_pct=$PCT ==="
    TAG="cxl_pct${PCT}"
    $GEM5 -d "$OUTDIR/$TAG" "$CFGDIR/oram_sim_cxl.py" \
        --binary=$BIN --num-instances=$N --num-ops=$OPS --num-slots=$SLOTS \
        --local-pct=$PCT \
        2>&1 | tee "$OUTDIR/${TAG}.log" | tail -3
    VALS=$(extract "$OUTDIR/${TAG}.log")
    echo "cxl,$PCT,$VALS" >> $RESULTS
    echo "  → $VALS"
    echo ""
done

echo ""
echo "=== RESULTS ==="
column -t -s, $RESULTS
echo ""
echo "CSV: $RESULTS"
echo "Plot: python3 configs/plot_local_pct.py $RESULTS"
